# Unique project name
name: aemeath

# Required BuildStream version
min-version: 2.6

# Subdirectory where elements are stored
element-path: elements

environment:
  LC_ALL: en_US.UTF-8

plugins:
  - origin: junction
    junction: bst-plugins.bst
    elements:
      - autotools
      - meson
      - cmake
      - make
      - setuptools
    sources:
      - docker
      - patch
  - origin: junction
    junction: bst-plugins-community.bst
    elements:
      - makemaker
      - pyproject
      - qmake
      - collect_manifest
    sources:
      - cpan
      - pypi
      - git_repo
      - git_module
      - go_module
      - gnu
      - cargo2
      - patch_queue
      - zip
  - origin: local
    path: plugins
    elements:
      - collect_initial_scripts
options:
  prod_keys:
    type: bool
    description: Use production boot keys
    default: False

sources:
  git_repo:
    config:
      ref-format: git-describe
  cargo2:
    config:
      url: crates:crates
      git-mirrors:
        https://github.com/: "github:"

elements:
  (@):
    - include/config/autotools.yml

(@):
  - include/install-dirs.yml
  - include/artifacts.yml
  - include/aliases.yml
  - include/flags-env.yml

variables:
  go-arch: amd64
  (@):
    - include/config/strip.yml
    - include/config/flags.yml
    - include/versions/track.yml
    - include/versions.yml
    - include/image-version.yml
