kind: stack

depends:
- components/sys-data/filesystem.bst
- components/sys-devel/binutils.bst
- components/sys-devel/gcc.bst
#- components/sys-devel/bison.bst
#- components/util-sys/coreutils.bst
#- components/util-sys/grep.bst
- components/util-sys/sed.bst
#- components/dev-tools/make.bst
#- components/util-shells/bash.bst
#- components/util-sys/diffutils.bst
#- components/util-sys/findutils.bst
#- components/util-sys/gawk.bst
#- components/util-archive/gzip.bst