alias ls='ls --color=auto'

# Non-interactive login shells do not set PS1. So we need to make sure
# to set it in interactive non-login shells from the same session.
export PS1='\[\e[92m\]\u\[\e[0m\]@\[\e[95m\]\h\[\e[0m\]:\[\e[94m\]\w\[\e[0m\]\$ '

if ! shopt -q login_shell; then
    for i in /etc/profile.d/*.sh; do
        if [ -r "${i}" ]; then
            . "${i}"
        fi
    done
fi
unset i

export PATH="${HOME}/.local/bin:${PATH}"
