kind: stack

depends:
  - components/kde-plasma/kdecoration.bst
  - components/kde-plasma/libkscreen.bst
  - components/kde-plasma/libksysguard.bst
  - components/kde-plasma/breeze.bst
  - components/kde-plasma/breeze-gtk.bst
  - components/kde-plasma/layer-shell-qt.bst
  - components/kde-plasma/plasma-activities.bst
  - components/kde-plasma/libplasma.bst
  - components/kde-plasma/kscreenlocker.bst
  - components/kde-plasma/kinfocenter.bst
  - components/kde-plasma/kwayland.bst
  - components/kde-plasma/aurorae.bst
  - components/kde-plasma/knighttime.bst
  - components/kde-plasma/kwin.bst
  - components/kde-plasma/plasma5support.bst
  - components/kde-plasma/kpipewire.bst
  - components/kde-plasma/plasma-workspace.bst
  - components/kde-plasma/plasma-disks.bst
  - components/kde-plasma/bluedevil.bst
  - components/kde-plasma/kde-gtk-config.bst
  - components/kde-plasma/kmenuedit.bst
  - components/kde-plasma/kscreen.bst
  - components/kde-plasma/kwallet-pam.bst
  - components/kde-plasma/kwrited.bst
  - components/kde-plasma/milou.bst
  - components/kde-plasma/plasma-nm.bst
  - components/kde-plasma/plasma-pa.bst
  - components/kde-plasma/plasma-workspace-wallpapers.bst
  - components/kde-plasma/polkit-kde-agent.bst
  - components/kde-plasma/powerdevil.bst
  - components/kde-plasma/plasma-desktop.bst
  - components/kde-plasma/ksshaskpass.bst
  - components/kde-plasma/discover.bst
  - components/kde-plasma/kactivitymanagerd.bst
  - components/kde-plasma/plasma-integration.bst
  - components/kde-plasma/xdg-desktop-portal-kde.bst
  - components/kde-plasma/drkonqi.bst
  - components/kde-plasma/plasma-vault.bst
  - components/kde-plasma/kde-cli-tools.bst
  - components/kde-plasma/systemsettings.bst
  - components/kde-plasma/plasma-thunderbolt.bst
  - components/kde-plasma/plasma-firewall.bst
  - components/kde-plasma/plasma-systemmonitor.bst
  # - components/kde-plasma/qqc2-breeze-style.bst
  - components/kde-plasma/ksystemstats.bst
  - components/kde-plasma/kdeplasma-addons.bst
  - components/kde-plasma/flatpak-kcm.bst
  - components/kde-plasma/plasma-welcome.bst
  - components/kde-plasma/ocean-sound-theme.bst
  - components/kde-plasma/print-manager.bst
  - components/kde-plasma/krdp.bst
  - components/kde-plasma/spectacle.bst
  - components/kde-plasma/plasma-login-manager.bst
  - components/kde-plasma/plasma-setup.bst
  - components/kde-plasma/plasma-keyboard.bst
  - components/kde-plasma/oxygen.bst
  - components/kde-plasma/oxygen-sounds.bst
  # Experimental things
  - components/kde-plasma/union.bst
  # obsolete things
  # - components/kde-plasma/wacomtablet.bst
  # - components/kde-plasma/oxygen.bst
  #- components/kde-plasma/oxygen-sounds.bst
  #- components/kde-plasma/kgamma.bst
  # - components/kde-plasma/sddm-kcm.bst
