kind: stack

depends:
  - components/plasma/kdecoration.bst
  - components/plasma/libkscreen.bst
  - components/plasma/libksysguard.bst
  - components/plasma/breeze.bst
  - components/plasma/layer-shell-qt.bst
  - components/plasma/plasma-activities.bst
  - components/plasma/libplasma.bst
  - components/plasma/kscreenlocker.bst
  - components/plasma/kinfocenter.bst
  - components/plasma/kwayland.bst
  - components/plasma/aurorae.bst
  - components/plasma/knighttime.bst
  - components/plasma/kwin.bst
  - components/plasma/plasma5support.bst
  - components/plasma/kpipewire.bst
  - components/plasma/plasma-workspace.bst
  - components/plasma/plasma-disks.bst
  - components/plasma/bluedevil.bst
