---
name: Update sources
on:
  schedule:
    - cron: "27 00 * * *" # 03:05am UTC everyday
  workflow_dispatch:

jobs:
  build_push:
    name: Track sources
    runs-on: ubuntu-latest

    permissions:
      contents: write

    container:
      image: registry.gitlab.com/freedesktop-sdk/infrastructure/freedesktop-sdk-docker-images/bst2:4387d0fa82f12808377dacc5feaf08a0d82a06af
      options: --privileged --device /dev/fuse
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          token: ${{ secrets.AEMEATH_GH_PAT }}
          fetch-depth: 0
      - name: Set up keys
        run: |
          echo "$DB_CRT" > files/boot-keys/DB.crt
          echo "$DB_KEY" > files/boot-keys/DB.key
          echo "$KEK_CRT" > files/boot-keys/KEK.crt
          echo "$KEK_KEY" > files/boot-keys/KEK.key
          echo "$MODULE_CRT" > files/boot-keys/linux-module-cert.crt
          echo "$MODULE_KEY" > files/boot-keys/linux-module-cert.key
          echo "$PK_CRT" > files/boot-keys/PK.crt
          echo "$PK_KEY" > files/boot-keys/PK.key
          echo "$VENDOR_CRT" > files/boot-keys/VENDOR.crt
          echo "$VENDOR_KEY" > files/boot-keys/VENDOR.key
          mkdir -p files/boot-keys/modules
          cp files/boot-keys/linux-module-cert.crt files/boot-keys/modules
        shell: bash
        env:
          DB_CRT: ${{secrets.DB_CRT}}
          DB_KEY: ${{secrets.DB_KEY}}
          KEK_CRT: ${{secrets.KEK_CRT}}
          KEK_KEY: ${{secrets.KEK_KEY}}
          MODULE_CRT: ${{secrets.MODULE_CRT}}
          MODULE_KEY: ${{secrets.MODULE_KEY}}
          PK_CRT: ${{secrets.PK_CRT}}
          PK_KEY: ${{secrets.PK_KEY}}
          VENDOR_CRT: ${{secrets.VENDOR_CRT}}
          VENDOR_KEY: ${{secrets.VENDOR_KEY}}
      - name: Track sources
        continue-on-error: true
        run: bst source track
      - name: Commit & push
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git config --global user.name "Aemeath OS Updates"
          git config --global user.email "aemeath@damillora.com"
          git add elements
          git commit -m "chore: bst source track" && git push
        shell: bash
